* Installing from github

Follow the link and install it. Do remember that you must clone the github and not download the zip file provided with the guide because it would not work (as it is outdated by now).

So install it.
https://askubuntu.com/questions/753748/can-anyone-tell-me-step-by-step-way-to-install-logkeys-keylogger-in-ubuntu-14-04


* Running it
After installation is done, you may run it. 

sudo logkeys --start --output .my_logger.log

You can view the logged activity using:

sudo tail .my_logger.log

You can kill the logger using:

sudo logkeys -k

* Keymap

If you read the log file using ~sudo cat .my_logger.log~, you will notice that the entire output is gibberish. Why?

The reason is, the keylogger must work for all types of keyboard architecture around the world and so, it produces raw output by default. You need to customize it for your keyboard and it is pretty easy!

First, logkeys github provide a list of keymaps for famous keyboard layouts. You may go through the files and see if it matches youtd.
https://github.com/kernc/logkeys/tree/master/keymaps

For example, mine matched with en_US_ubuntu.map so I copied its contents and pasted it into a temp.map file. Now i will run the following command.

sudo logkeys --start --keymap=temp.map --output .my_logger.log

Voila! It will work perfectly fine now. If you view the log file, you will see that the output is very sane now.
sudo cat .my_logger.log

Thats about everything.
