
* About
A lot of automation tasks are needed in our day to day life. I will share them here to help others who might need them. Lets grow together.
Feel free to push your automation scripts here. I would love contributions. For any query, feel free to raise an issue.
* Automations
The following automations were done so far.
** Automate NMAP analysis
This site runs a bunch of nmap commands for a given site. It can help you generate reconnaisance analysis for a site easily.
The details of each nmap script are commented beside the script.
*** Installation
To install it, execute the following commands.
#+begin_src bash
  git clone https://github.com/abj-paul/Automate-Stuffs
  cd Automate-Stuffs
  sudo chmod u+x automate.sh
  ./automate.sh examplesite.com
#+end_src
*** Output
All analysis are stored in their separate files. Hopefully the names of the files help you recognize them. If you have some confusion as to what content a file have, you can view the command at the top of the file or you can just go to the script code. Each code is explained there.
#+begin_src text
├── automate.sh
└── examplesite.org
    ├── examplesite.org.all.txt
    ├── examplesite.org.domain.txt
    ├── examplesite.org.ids_all.txt
    ├── examplesite.org.mixed_port_scan.txt
    ├── examplesite.org.port_scan.txt
    ├── examplesite.org.random_servers.txt
    ├── examplesite.org.range_port_scan.txt
    ├── examplesite.org.scan_ack_port.txt
    ├── examplesite.org.scan_list_targets.txt
    ├── examplesite.org.scan_syn_port.txt
    ├── examplesite.org.scan_tcp_port.txt
    ├── examplesite.org.scan_udp_port.txt
    ├── examplesite.org.script_crossite.txt
    ├── examplesite.org.script_default.txt
    ├── examplesite.org.script_open_ports.txt
    ├── examplesite.org.script_sitemap.txt
    ├── examplesite.org.service_intensity.txt
    ├── examplesite.org.service.txt
    ├── examplesite.org.sitemap.txt
    ├── examplesite.org.target_specification.txt
    ├── examplesite.org.tcp_list_targets.txt
    └── examplesite.org.udp_list_targets.txt

1 directory, 24 files
#+end_src
